spring:
  application:
    name: sistema-inventario

  datasource:
    url: jdbc:mysql://localhost:3306/sistema_inventario?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.castores.inventario: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
